export const data = {
  websiteTitle: 'g-perf',
  cardTitle: `Ceci est un titre`,
  cardBody: `Lorem ipsum dolor sit amet <a href='https://www.google.fr/' target='_blank'>CECI EST UN LIEN</a>, consectetur adipiscing elit. Vestibulum urna dui, tristique vitae nisi at, tincidunt porttitor diam. Nunc pharetra odio at lacinia rhoncus. Donec sed ante aliquet, finibus nisi at, laoreet risus. Duis ac mattis turpis, sit amet pulvinar mi. Nullam consequat id ligula eget elementum. Fusce venenatis leo non sollicitudin cursus. Morbi eros justo, commodo eget metus a, pellentesque mollis lacus. Aenean eget ligula pellentesque, efficitur est eget, pellentesque mi. Nunc vitae posuere felis, sit amet semper nibh. Phasellus ornare cursus magna a vulputate.

  Aliquam semper sem in finibus tristique. Duis tempor eu sem accumsan dignissim. Vestibulum interdum, metus sed commodo sollicitudin, mauris dolor eleifend enim, in fermentum dolor elit non turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec id orci ac libero vulputate efficitur in dignissim orci. Aliquam convallis velit eu tortor tincidunt, sit amet faucibus erat finibus. Nulla rhoncus magna vitae tincidunt scelerisque.
  
  Cras ac lacus sed diam aliquam tempus nec et elit. Cras dignissim enim quis erat dignissim, ac posuere purus ultrices. Phasellus eu urna purus. Ut vitae tincidunt massa. Vivamus accumsan nibh quis vehicula scelerisque. Suspendisse congue in tortor et hendrerit. Etiam tincidunt bibendum leo sed cursus. Phasellus id ex sed quam commodo pretium. Vivamus cursus hendrerit neque, vel tincidunt urna suscipit eget. Suspendisse malesuada, nisi sed euismod finibus, tortor ipsum mattis arcu, vitae faucibus dui nulla in ipsum. Mauris nec velit eget eros tempus porttitor eget at est. Phasellus vehicula porta erat, commodo fringilla est ullamcorper convallis. Phasellus auctor finibus odio a porttitor. Suspendisse vitae facilisis erat. Nam ultrices quis arcu elementum viverra.
  
  Donec molestie, ex id dapibus venenatis, diam tellus iaculis nulla, sed ornare nisl ex vel purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed quis egestas dolor. Suspendisse purus leo, consequat in pretium quis, fermentum non turpis. Integer sed elementum justo, sed malesuada magna. Sed eu condimentum mi, ac tempus nibh. Donec nec arcu et nibh tempus cursus. Nunc non dolor a nisi pellentesque tristique.
  
  Sed fermentum ex vel mauris tempus lacinia. Sed ac lacus purus. Nunc ornare, ligula id maximus dictum, eros justo fermentum mi, vestibulum laoreet odio risus eget lacus. Nunc magna orci, sagittis laoreet auctor vel, pretium sollicitudin turpis. Sed ullamcorper elementum ipsum eget maximus. Maecenas felis purus, commodo eu urna eu, porta venenatis mauris. Vestibulum nulla erat, tristique eget ligula et, cursus semper est. Integer non risus nisi. Aenean sollicitudin accumsan vulputate. Phasellus at nisi nibh. Aliquam eget fermentum neque, eget imperdiet metus. Fusce eget dapibus erat, vitae viverra orci. Morbi sit amet eros commodo risus pretium auctor.`
}